<script setup lang="ts">
import {fetchSceneAndMount_scene_01} from './polygonjs/scenes/scene_01/autogenerated/fetchSceneAndMount';
const loadedData = await fetchSceneAndMount_scene_01({
    domElement: 'app',

});
const {scene} = loadedData;
// get a node
const node = scene.node('/lights/polarTransform1');
// access a parameter with .p and set the value
node.p.latitude.set(100);

</script>

<template>
	<Scene01 />
	<a class="page-title" href="https://polygonjs.com">
		<img class="page-title-logo" src="/polygonjs.png" />
		<span class="page-title-text">Polygon + Vue + TS</span>
	</a>
</template>

<style scoped></style>
